spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/financeiroIntegracao?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: cassio
    password: 123

server:
  port: 8082
#server:
#  port: ${PORT:${SERVER_PORT:0}}
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/

