spring:
  jpa: 
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/academico?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: cassio
    password: 123
    
server:
  port: 8080

#server:
#  port: ${PORT:${SERVER_PORT:0}}


eureka:
  client: 
    serviceUrl: 
      defaultZone: http://localhost:8090/eureka/     
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}