spring:
  application:
    name: web-gateway

server:
  port: 80
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
      
zuul: 
#  prefix: /v2
  ignored-services: msendereco
  routes:
    msfinanceiro:
       path: msfinanceiro/**
    msacademico:
       path: msacademico/**
    msintegracaofinanceira:
       path: msintegracaofinanceira/**
    msrelatorios:
       path: msrelatorios/**   
